# Generated by Django 6.1.1 on 2026-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="cpf",
            field=models.CharField(blank=True, default="", max_length=14),
        ),
        migrations.AddField(
            model_name="note",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="note",
            name="secret",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="note",
            name="token",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
