# Generated by Django 6.1.1 on 2026-09-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("restore", "Restore"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("custom", "Custom"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("user_type", models.CharField(blank=True, max_length=255, null=True)),
                ("object_id", models.CharField(max_length=255)),
                ("meta_info", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("request_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "audivra_audit_log",
                "ordering": ["-created_at"],
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(fields=["content_type", "object_id", "created_at"], name="audivra_obj_history_idx"),
                    models.Index(fields=["user_id"], name="audivra_user_idx"),
                    models.Index(fields=["created_at"], name="audivra_created_idx"),
                    models.Index(fields=["action"], name="audivra_action_idx"),
                ],
            },
        ),
    ]
