# Generated by Django 6.1.1 on 2026-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audivra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="event_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="AuditOutbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(unique=True)),
                ("event_type", models.CharField(max_length=16)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "audivra_audit_outbox",
                "ordering": ["id"],
                "indexes": [models.Index(fields=["status", "created_at"], name="audivra_outbox_status_idx")],
            },
        ),
    ]
